services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - explorer_network

  web:
    build: .
    container_name: explorer-web
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - ./storage:/app/storage
    command: gunicorn -c gunicorn.conf.py run:app
    depends_on:
      - rabbitmq
    networks:
      - explorer_network

  worker:
    build:
      context: .
    container_name: explorer-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./storage:/app/storage
    networks:
      - explorer_network
    command: >
      python rabbit_worker.py


networks:
  explorer_network:
    driver: bridge

volumes:
  storage_data:
